name: Simple Workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Fetch origin
        run: git fetch origin $GITHUB_BASE_REF
        
      - name: Install dependencies
        run: |
           sudo apt-get update
           sudo apt install python3

      - name: Run python file
        run: python simple.py
