name: Simple Workflow

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
           sudo apt-get update
           sudo apt install python3

      - name: Run python file
        run: python simple.py
